main: at.lukasf.taxfreeregion.TaxFreeRegion
version: 1.7
name: TaxFreeRegion
author: adreide, tickleman, fruel
depend: [WorldEdit]
softdepend: [WorldGuard]
commands:
  taxfree:
    aliases: tf
    description: 'Tax Free Regions Command'
    usage: |
      TaxFreeRegion v1.7
      /<command> list
      /<command> add NAME [WorldGuard Region|World]
      /<command> delete
      /<command> reload
      /<command> clear
      /<command> reward
permissions:
  taxfreeregion.*:
    default: op
    description: Allow you to have full access to TaxFreeRegion plugin without having the inventory cleared.
    children:
      taxfreeregion.passthrough: true
      taxfreeregion.use: true
      taxfreeregion.clear: true
  taxfreeregion.passthrough:
    default: op
    description: Users that have this will not be affected by entering a region
  taxfreeregion.use:
    default: op
    description: Permits to add/list and remove taxfreeregions
  taxfreeregion.clear:
    default: op
    description: Allows usage of /tf clear
